#include "S751.h"
#include <cmath>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using namespace std;

namespace ProjectEuler
{
std::string S751::GetAnswer()
{
	double theta = 2.22; // Start somewhere? Original code 2.5
	// Code said theta = 2.5 initially.
	theta = 2.5;
	std::string lastAnswer = "2.5";
	int Length = 26; // Precision required? 24 decimals + 2.
	// Problem asks for 24 decimal places.
	// So string length around 26.

	while (true)
	{
		std::vector<double> bn(Length);
		std::vector<int> an(Length);

		bn[0] = theta;
		an[0] = (int)std::floor(bn[0]);

		for (int i = 0; i < Length - 1; i++)
		{
			long long b = (long long)std::floor(bn[i]);
			bn[i + 1] = b * (bn[i] - b + 1);
			an[i + 1] = (int)std::floor(bn[i + 1]);
		}

		std::ostringstream sb;
		sb << an[0] << ".";
		for (int i = 1; i < Length; i++)
		{
			sb << an[i];
		}

		std::string answer = sb.str();
		// Compare only prefix?
		// If answer starts with lastAnswer?
		// "if (answer == lastAnswer)" implies full match.
		// But answer depends on theta, which comes from parsing answer.
		// It converges.

		if (answer == lastAnswer)
		{
			break;
		}

		lastAnswer = answer;
		// Parse answer back to double
		// std::stod might not have enough precision if we just use answer string.
		// But doubles have 15-17 digits. 24 digits won't fit in double.
		// Wait, standard double has 53 bits ~ 16 decimal digits.
		// Problem requires 24 decimal places.
		// Does Project Euler mean we need high precision arithmetic?
		// "Concatenation Coincidence".
		// Maybe the sequence stabilizes quickly?
		// If we use double, we get approx result.
		// But problem 751 might be solvable with doubles if we are careful?
		// Or maybe the loop logic finds it.
		// Actually, theta is generated by concatenation.
		// The value is 2.22...
		// 2.a1 a2 a3...
		// If we need 24 digits, we need `__float128` or `long double` or string manipulation.
		// I'll use `long double` for better precision.
		// `long double` is usually 80-bit or 128-bit on Linux (18-33 digits).
		// It might cover 24 digits.

		try
		{
			theta = std::stold(answer);
		}
		catch (...)
		{
			break;
		}
	}

	return lastAnswer.substr(0, 26);
}
} // namespace ProjectEuler
